### ISSUE TITLE
请教一个入门问题

### ISSUE THREAD

**Issue by 0535** [kong36088/YanPHP#1]
将`Application\Cgi`目录下的内容复制到本地虚拟目录(`a.com`)下，访问`a.com/interface.php/Hello/index`，给出提示信息如下：
`{"code":5001,"message":"404 Not Found","data":[]}`
并没有看到
```
{
    "code": 0,
    "message": "hello world",
    "data": []
}
```
请问，可不可以给一个部署的步骤。。。
PS：`interface.php`中的目录信息已做修改了。

**Comment by kong36088** [comment]
麻烦贴一下interface.php文件内容、Cgi/Param目录下文件列表，同时请问您运行过 `composer install`命令进行框架组件的安装了吗？

**Comment by kong36088** [comment]
同时，因为框架使用的是composer进行包管理，所以在新增了Controller或Model等类库文件后需要运行一次`composer update`命令以刷新autoloader

**Comment by 0535** [comment]
上午运行`composer install`的时候还没有报错，刚才运行`composer update`居然报错。
![default](https://user-images.githubusercontent.com/11014548/32766495-26368cc4-c94a-11e7-9ad0-230eef0b39de.jpg)
我在换个环境试一下吧。。。

---

`interface.php`如下
``` php
<?php
/**
 * User: weilongjiang(江炜隆)<willliam@jwlchina.cn>
 * Date: 2017/8/23
 * Time: 17:06
 */
$debug = true;
if ($debug) {
    ini_set('display_errors', 1);            //错误信息
    ini_set('display_startup_errors', 1);    //php启动错误信息
    error_reporting(-1);                    //打印出所有的 错误信息
}

$systemPath = '../YanPHP/System';
$cachePath = 'cache';
defined('SELF') or define('SELF', pathinfo(__FILE__, PATHINFO_BASENAME));
defined('SYS_PATH') or define('SYS_PATH', rtrim($systemPath, '/\\'));
defined('BASE_PATH') or define('BASE_PATH', dirname(__FILE__));
defined('CACHE_PATH') or define('CACHE_PATH', $cachePath);

require_once "../YanPHP/System/yan.php";
```

其它文件是复制`Application/Cgi`目录的。。。
